version: "3.9"

name: interbook

services:
  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=${PSQLDB}
      - POSTGRES_PASSWORD=${PSQLP}
      - POSTGRES_USER=${PSQLU}
    ports:
      - "5432:5432"
    volumes:
      - ../data/psql-data:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDISPASS}
    volumes:
      - ../data/redis-data:/data

  node:
    build:
      dockerfile: ../backend/Dockerfile
      context: ../backend
    environment:
      - PORT=${NODE_PORT}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - ../backend/src:/app/src
    depends_on:
      - cache
      - postgres